{
 "title": "Kafka Dashboard",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus",
  "kafka",
  "microservices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "kafka:9308" },
   { "name": "topic", "label": "topic", "query": "topic" }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "dthms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(process_cpu_seconds_total{instance=~\"$instance\"}/(time()-process_start_time_seconds{instance=\"$instance\"}))*100"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=\"$instance\"}",
     "legendFormat": "deadlocked"
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Last Stable Offset Lag",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_cluster_partition_laststableoffsetlag{instance=\"$instance\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Free Heap",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1-(jvm_memory_bytes_used{area=\"heap\", instance=\"$instance\"}/jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}))*100"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "rate(in) bytes/sec and rate(out) bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{instance=\"$instance\", topic!~\".+\"}[1m])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{instance=\"$instance\", topic!~\".+\"}[1m])",
     "legendFormat": "out"
    }
   ]
  },
  { "title": "Kafka Messaging Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Messages In (Total per topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{instance=\"$instance\", topic=~\".+\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Log Size (per topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{instance=\"$instance\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Average Message Size (per topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{instance=\"$instance\"}/kafka_server_brokertopicmetrics_messagesin_total{instance=\"$instance\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Message Bytes (per Topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{instance=\"$instance\", topic=~\".+\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Message Bytes (per Topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{instance=\"$instance\", topic=~\".+\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}  / ignoring(area) group_left process_resident_memory_bytes{instance=~\"$instance\"} *100",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}