{
 "title": "MicroServices Drilldown Metrics",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "tags": [
  "prometheus",
  "spring-boot",
  "services"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "environment",
    "query": "label_values(jvm_classes_loaded_classes{instance=\"$instance\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes, instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_classes_loaded_classes{instance=\"$instance\"}, appName)"
   },
   {
    "name": "instanceId",
    "label": "instanceId",
    "query": "label_values(jvm_classes_loaded_classes{instance=\"$instance\"}, instanceId)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", appName=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{appName=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{appName=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{appName=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{appName=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{appName=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{appName=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{appName=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Successful HTTP Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{appName=\"$application\", env=\"$env\", outcome=\"SUCCESS\", uri!~\".*actuator.*\"})"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{appName=\"$application\", env=\"$env\", outcome!~\"SUCCESS\", uri!~\".*actuator.*\"})"
    }
   ]
  },
  {
   "title": "Service Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(component_invocation_exception_counter_total{appName=\"$application\", env=\"$env\", componentType=\"service\"})"
    }
   ]
  },
  {
   "title": "DAO Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(component_invocation_exception_counter_total{appName=\"$application\", env=\"$env\", componentType=\"dao\"})"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "HTTP/Controller Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Successful HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", appName=\"$application\", uri!~\".*actuator.*\", outcome=\"SUCCESS\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Average Successful HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"$instance\", appName=\"$application\", exception=\"None\", uri!~\".*actuator.*\", outcome=\"SUCCESS\"} / http_server_requests_seconds_count{instance=\"$instance\", appName=\"$application\", exception=\"None\", uri!~\".*actuator.*\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Failed HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", appName=\"$application\", uri!~\".*actuator.*\", outcome!~\"SUCCESS\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Maximum HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", appName=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Service Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(component_invocation_timer_seconds_count{instance=\"$instance\", appName=\"$application\", componentType=\"service\"}[1m])",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  {
   "title": "Avg. Service Invocation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "component_invocation_timer_seconds_sum{instance=\"$instance\", appName=\"$application\", componentType=\"service\"}/component_invocation_timer_seconds_count{instance=\"$instance\", appName=\"$application\", componentType=\"service\"}",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  {
   "title": "Service Exceptions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "component_invocation_exception_counter_total{appName=\"$application\", instance=\"$instance\", componentType=\"service\"}",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  { "title": "DAO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "DAO Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(component_invocation_timer_seconds_count{instance=\"$instance\", appName=\"$application\", componentType=\"dao\"}[1m])",
     "legendFormat": "{{componentClass}}"
    }
   ]
  },
  {
   "title": "Avg. DAO Invocation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "component_invocation_timer_seconds_sum{instance=\"$instance\", appName=\"$application\", componentType=\"dao\"}/component_invocation_timer_seconds_count{instance=\"$instance\", appName=\"$application\", componentType=\"dao\"}",
     "legendFormat": "{{componentClass}}"
    }
   ]
  },
  {
   "title": "DAO Exception Counts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "component_invocation_exception_counter_total{appName=\"$application\", instance=\"$instance\", componentType=\"dao\"}",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  {
   "title": "Integration - Custom Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "Integration Components Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(component_invocation_timer_seconds_count{instance=\"$instance\", appName=\"$application\", componentType=\"integration\"}[1m])",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  {
   "title": "Avg. Integration Components Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "component_invocation_timer_seconds_sum{instance=\"$instance\", appName=\"$application\", componentType=\"integration\"}/component_invocation_timer_seconds_count{instance=\"$instance\", appName=\"$application\", componentType=\"integration\"}",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  {
   "title": "Integration Exceptions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "component_invocation_exception_counter_total{appName=\"$application\", instance=\"$instance\", componentType=\"integration\"}",
     "legendFormat": "{{componentClass}}-{{methodName}}"
    }
   ]
  },
  {
   "title": "Integration - HTTP Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "HTTP Client - Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{instance=\"$instance\", appName=\"$application\"}[1m])",
     "legendFormat": "{{methodName}}[{{status}}]"
    }
   ]
  },
  {
   "title": "Avg. HTTP Client Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds_sum{instance=\"$instance\", appName=\"$application\"}/http_client_requests_seconds_count{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "{{methodName}}[{{status}}]"
    }
   ]
  },
  {
   "title": "Service Invocation Counts",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "http_client_requests_seconds_count{appName=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Integration - Kafka Producer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 }
  },
  {
   "title": "kafka_producer_record_send_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total{appName=\"$application\", instance=\"$instance\", env=\"$env\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "kafka_producer_outgoing_byte_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_outgoing_byte_total{env=\"$env\", appName=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "kafka_producer_record_retry_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_retry_total{appName=\"$application\",env=\"$env\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Integration - Kafka Consumer Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }
  },
  {
   "title": "Kafka Total Records Consumed by InstanceId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, instanceId) (kafka_consumer_records_consumed_total_records_total{env=\"$env\", appName=\"$application\", instance=\"$instance\"})",
     "legendFormat": "{{instanceId}}- {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Total Records Consumed by InstanceId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, instanceId) (kafka_consumer_bytes_consumed_total_bytes_total{env=\"$env\", appName=\"$application\", instance=\"$instance\"})",
     "legendFormat": "{{instanceId}}- {{topic}}"
    }
   ]
  },
  {
   "title": "Assigned Kafka Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instanceId) (kafka_consumer_assigned_partitions{appName=\"$application\", env=\"$env\", client_id!~\".*restore.*\", instance=\"$instance\"})",
     "legendFormat": "instanceId - {{instanceId}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Average Lag by Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, instanceId) (kafka_consumer_records_lag_avg_records{appName=\"$application\", env=\"$env\", client_id!~\".*restore.*\", instance=\"$instance\"})",
     "legendFormat": "{{topic}}-{{instanceId}}"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", appName=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", appName=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 126 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", appName=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", appName=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", appName=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", appName=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 134 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{appName=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{appName=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", appName=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", appName=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "JDBC Connection Pool Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Connection Pool Max. Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 153 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_max{instance=\"$instance\", appName=\"$application\"}"
    }
   ]
  },
  {
   "title": "JDBC Active Connections Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Avg. JDBC Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 153 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_max{instance=\"$instance\", appName=\"$application\"}/hikaricp_connections_usage_seconds_count{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Avg. JDBC Connection acquire time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 161 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", appName=\"$application\"}/hikaricp_connections_acquire_seconds_count{instance=\"$instance\", appName=\"$application\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}